In [2]:
import numpy as np

In [7]:
'''Q1:- Create a Numpy array of these stock prices:
150, 152, 148, 155, 160, 158, 162
Then print the mean, max and min price.'''

arr = np.array([150, 152, 148, 155, 160, 158, 162])

print(arr)
print()
print(np.mean(arr))
print()
print(np.max(arr))
print()
print(np.min(arr))

[150 152 148 155 160 158 162]

155.0

162

148


In [8]:
'''Q2:- You have two arrays:
buy_price = np.array([100, 200, 150])
sell_price = np.array([120, 180, 175])
Calculate the profit for each stock (sell-buy).
'''
buy_price = np.array([100, 200, 150])
sell_price = np.array([120, 180, 175])

profit = sell_price - buy_price
print(profit)

[ 20 -20  25]


In [15]:
'''Q3:- Create an array of 10 zero -- then replace the 5th element with 99.'''
ar_zero = np.zeros(10)
print(ar_zero)
print()
ar_zero[4] = 99
print(ar_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[ 0.  0.  0.  0. 99.  0.  0.  0.  0.  0.]


In [56]:
'''Q4 Given this array of daily closing prices:
prices = np.array([100, 105, 103, 110, 108, 115])
Calculate the daily return for each day using: '''

prices = np.array([100, 105, 103, 110, 108, 115])
daily_returns = (prices[1:] - prices[:-1])/ prices[:-1]
print(np.round(daily_returns, 3))


[ 0.05  -0.019  0.068 -0.018  0.065]


In [5]:
'''Q5:- From the same prices array, calculate the standard deviation of daily returns.'''
prices = np.array([100, 105, 103, 110, 108, 115])
returns = (prices[1:] - prices[:-1])/ prices[:-1]
std_dev = np.std(returns)
print("Daily Returns:", np.round(returns, 3))
print("Standard Deviation of Returns:", std_dev)

Daily Returns: [ 0.05  -0.019  0.068 -0.018  0.065]
Standard Deviation of Returns: 0.03943681341963744


In [58]:
'''Q6:-You have a 2D array:
data = np.array([
        [100, 102, 105,103], #Stock A
        [200, 198, 201, 205], #Stock B
        [50, 52, 51, 55], #Stock C
])
. Print the price of Stock B on Day3
. print all prices of stock A
. print prices of all stock on Day4'''

data = np.array([[100, 102, 105,103], #Stock A
                 [200, 198, 201, 205], #Stock B
                 [50, 52, 51, 55], #Stock C
])
print("Print the price of Stock B on Day3", data[1,2])
print()
print("print all prices of stock A", data[0,:])
print()
print("print prices of all stock on Day4", data[:,3])

Print the price of Stock B on Day3 201

print all prices of stock A [100 102 105 103]

print prices of all stock on Day4 [103 205  55]


In [6]:
'''Q7. Given daily returns:
returns = np.array([0.01, -0.02, 0.015, 0.03, -0.01])
Calculate the cumulative return using np.cumprod().'''
prices = np.array([0.01, -0.02, 0.015, 0.03, -0.01])
returns = (prices[1:] - prices[:-1])/ prices[:-1]
cumulative_returns = np.cumprod(1 + returns)
print("Daily_Returns:", np.round(returns, 3))
print("cumulative_returns", cumulative_returns)

Daily_Returns: [-3.    -1.75   1.    -1.333]
cumulative_returns [-2.   1.5  3.  -1. ]


In [47]:
'''Q8:- Generate 252 random daily returns with mean 0.001 and std 0.02, the annualized volatility.
annualized vol = daily std * v252'''
mean = 0.001
std = 0.02
num_days = 252
np.random.seed(42)
daily_returns = np.random.normal(loc=mean, scale=std, size=num_days)
daily_std = np.std(daily_returns)
annualized_vol = daily_std * np.sqrt(252)

print(f"Daily std (volatility): {daily_std:.3f}")
print(f"Annualized Volatility: {annualized_vol:.4f}")

Daily std (volatility): 0.019
Annualized Volatility: 0.3065


In [49]:
'''Q9:- Given:
prices = np.array([100, 105, 103, 110, 108, 115, 120, 118, 125, 130])
Calculate the 5-day moving average using a loop and Numpy slicing.'''
prices = np.array([100, 105, 103, 110, 108, 115, 120, 118, 125, 130])
window_size = 5
moving_averages = []

for i in range(len(prices)- window_size + 1):
    window = prices[i : i + window_size]
    window_average = np.sum(window)/window_size
    moving_averages.append(window_average)

print(np.array(moving_averages))
    

[105.2 108.2 111.2 114.2 117.2 121.6]


In [55]:
'''Q10:- Given:
stock_a = np.array([0.01, 0.02, -0.01, 0.03])
stock_b = np.array([0.02, 0.01, 0.015, -0.01])
stock_c = np.array([-0.01, 0.03, 0.02, 0.01]) 
Stack them into a 2D array and calculate the average return per stock in one line.'''
stock_a = np.array([0.01, 0.02, -0.01, 0.03])
stock_b = np.array([0.02, 0.01, 0.015, -0.01])
stock_c = np.array([-0.01, 0.03, 0.02, 0.01]) 

average_returns = np.vstack([stock_a, stock_b, stock_c]).mean(axis=1)

print(average_returns)


[0.0125  0.00875 0.0125 ]
